### ISSUE TITLE
Is this only for Linux + x86/x64?

### ISSUE THREAD

**Issue by corwin-of-amber** [VojtechStep/jscoq-nix#1]
I am embarrassed at how little I know Nix, but after `nix flake init` I get these lines in `flake.nix`:
```
    with flake-utils.lib; eachSystem [
      system.x86_64-linux
      system.i686-linux
    ]
```

Does this mean it cannot be run on macOS + aarch64?

**Comment by VojtechStep** [comment]
Yes, currently I only set the supported systems to 32bit and 64bit Linux, because I don't have a Mac to test it on Darwin.

**Comment by corwin-of-amber** [comment]
If you give me a tip on what to add there I can try :) just `system.aarch64-darwin`?

**Comment by VojtechStep** [comment]
IIUC for building jsCoq on macOS, you can't use the "build Coq for 32bit platform and use that", right? I haven't implemented the part corresponding to `toolchain-setup.sh --64` (yet).
How it works now is that for both linux x86_64 and linux i686, it accesses two package sets - one for the native system, and one for the 32bit version of the system (so on x86_64 they are different). Then, all the OCaml and Coq stuff is compiled in the 32bit context, and where possible it uses native packages (for example for nodejs).

I _think_ the corresponding procedure for running on macOS aarch64 would be to take the 32bit packages from `i686-darwin`? Meaning that you would want to add `system.aarch64-darwin` to the list, and then also change the hardcoded string on L37 to "i686-darwin".

But I'd guess that if you recommend using patched x86_64 Coq for jsCoq because of some system limitations (that I haven't quite looked into tbf), the same limitations would apply for Nix.

**Comment by VojtechStep** [comment]
So I tried adding the sort of macOS support I was talking about above, but apparently Nix doesn't even have support for i686-darwin - the `nixpkgs` flake doesn't have an `i686-darwin` attribute, and using the stable ("old") Nix interface, I can't even build `hello` for `i686-darwin`:

```shell
adalbert@AdalbertDEV ~ [1]> nix-build -E '(import <nixpkgs> {system="i686-darwin";}).hello'
error: cannot coerce null to a string

       at /nix/store/sn1babgryzyqd1h3z7a0f4hz3ibiy15c-nixpkgs-22.05pre344883.27d2fe1e69d/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:224:60:

          223|           then attrs.name + hostSuffix
          224|           else "${attrs.pname}${staticMarker}${hostSuffix}-${attrs.version}";
             |                                                            ^
          225|     }) // {
(use '--show-trace' to show detailed location information)
```
Which seems to be an issue with `stdenv.cc`, which makes sense - can you check if you can build at least `hello` for `i686-darwin`? If not, I'm afraid I'll have to find some more time to add bespoke support for macOS.

**Comment by corwin-of-amber** [comment]
That would probably not work. Apple removed 32-bit support a few years back, which is why macOS builds use the `--64` flag. It *should* work fine. There is a patch that makes the `.vo` files generated by the 64-bit `coqc` binary-compatible with the 32-bit jsCoq runtime. It is brittle but worked for us so far. I see no way around it short of full processor emulation.

The `--64` flag is actually the default on macOS now.

**Comment by VojtechStep** [comment]
All right, I'll try and toy with it, probably over the weekend.

**Comment by VojtechStep** [comment]
@corwin-of-amber could you check if the `darwin-support` branch works for you?

The simplest way would be via the included template:
```bash
mkdir jscoq-test && cd jscoq-test
nix flake init -t github:VojtechStep/jscoq-nix/darwin-support
vim flake.nix # change `url = "github:VojtechStep/jscoq-nix";` to `url = "github:VojtechStep/jscoq-nix/darwin-support";`
nix build && python -m http.server --directory result
```
and then check if http://localhost:8000 works.

**Comment by corwin-of-amber** [comment]
Alright! That worked! I can load your `Basic.Module2`, and I can also run a dev shell which seems to have `jscoq` and `coqc` binaries. I'd like to see if I can build libraries now. I usually build libraries with Dune and Dune normally relies on OPAM switches, so I wonder whether this could work.

**Comment by VojtechStep** [comment]
I'm not really versed in the OCaml ecosystem - for building jsCoq, I replace the switch directive in dune-workspace with the `default` switch, and delegate all the OPAM stuff to [opam-nix](https://github.com/tweag/opam-nix/).
The main purpose of this flake was to get a jsCoq+coq combination so that I can build a package with dependencies on Coq's stdlib, and run it in the browser - since the textbook that uses it won't depend on any other libraries.

I have some free time that I can spend on this, so please open another issue if you hit problems with integrating it into your workflow. I will merge darwin support into main and close this issue.
